import org.yaml.snakeyaml.Yaml

buildscript {
    repositories { mavenCentral() }
    dependencies {
        classpath("org.yaml:snakeyaml:2.3")
    }
}

dependencies {
    implementation(libs.kotlin.stdlib)

    testImplementation(libs.kotest.runner.junit5)
    testImplementation(libs.kotest.assertions.core)
    testImplementation(libs.kotlin.test)
}

val sharedConstantsYaml = rootProject.file("../shared-constants.yaml")
val generatedSrcDir = layout.buildDirectory.dir("generated/sources/sharedConstants/kotlin/main")

val generateSharedConstants =
    tasks.register("generateSharedConstants") {
        group = "build"
        description = "Generates dev.yaytsa.shared.generated.Constants from /shared-constants.yaml"

        inputs.file(sharedConstantsYaml)
        outputs.dir(generatedSrcDir)

        doLast {
            @Suppress("UNCHECKED_CAST")
            val doc = sharedConstantsYaml.inputStream().use { Yaml().load<Map<String, Any?>>(it) }

            @Suppress("UNCHECKED_CAST")
            val constants = (doc["constants"] as? Map<String, Any?>).orEmpty()

            @Suppress("UNCHECKED_CAST")
            val enums = (doc["enums"] as? Map<String, List<String>>).orEmpty()

            val sb = StringBuilder()
            sb.appendLine("package dev.yaytsa.shared.generated")
            sb.appendLine()
            sb.appendLine("// AUTOGENERATED from /shared-constants.yaml — do not edit.")
            sb.appendLine("// Run `./gradlew :core-domain:shared:generateSharedConstants` to regenerate.")
            sb.appendLine()
            sb.appendLine("object Constants {")
            constants.forEach { (name, value) ->
                require(value is Number) { "Constant $name must be a number, got ${value?.javaClass}" }
                sb.appendLine("    const val $name: Long = ${value.toLong()}L")
            }
            sb.appendLine("}")
            sb.appendLine()
            enums.forEach { (name, values) ->
                sb.appendLine("enum class $name {")
                values.forEach { v -> sb.appendLine("    $v,") }
                sb.appendLine("}")
                sb.appendLine()
            }

            val outDir = generatedSrcDir.get().asFile
            outDir.mkdirs()
            outDir.resolve("Constants.kt").writeText(sb.toString())
            logger.lifecycle("generated: ${outDir.resolve("Constants.kt").absolutePath}")
        }
    }

sourceSets.named("main") {
    java.srcDir(generateSharedConstants.map { generatedSrcDir })
}

tasks.named("compileKotlin").configure {
    dependsOn(generateSharedConstants)
}
