spring:
  jpa:
    hibernate:
      ddl-auto: validate

management:
  server:
    port: ${MANAGEMENT_SERVER_PORT:9090}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: false
  paths-to-exclude: /rest/**

logging:
  level:
    dev.yaytsa: INFO
    org.hibernate.SQL: WARN
    org.springframework.security: WARN
