spring:
  jpa:
    hibernate:
      ddl-auto: validate

management:
  server:
    port: ${MANAGEMENT_SERVER_PORT:9090}

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

  datasource:
    hikari:
      maximum-pool-size: ${HIKARI_MAX_POOL:10}
      minimum-idle: ${HIKARI_MIN_IDLE:5}
      connection-timeout: 30000
      idle-timeout: 600000

logging:
  level:
    dev.yaytsa: INFO
    org.hibernate.SQL: WARN
    org.springframework.security: WARN
