apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgres-pgvector.fullname" . }}
  labels:
    {{- include "postgres-pgvector.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: postgresql
      port: {{ .Values.service.port }}
      targetPort: postgresql
      protocol: TCP
  selector:
    {{- include "postgres-pgvector.selectorLabels" . | nindent 4 }}
