{{- if and .Values.ingress.enabled .Values.backend.enabled .Values.ingress.secureHeaders.enabled }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "yay-tsa-v2.fullname" . }}-secure-headers
  labels:
    {{- include "yay-tsa-v2.labels" . | nindent 4 }}
spec:
  headers:
    stsSeconds: {{ int .Values.ingress.secureHeaders.stsSeconds }}
    stsIncludeSubdomains: {{ .Values.ingress.secureHeaders.stsIncludeSubdomains }}
    stsPreload: {{ .Values.ingress.secureHeaders.stsPreload }}
    forceSTSHeader: true
    {{- with .Values.ingress.secureHeaders.contentSecurityPolicy }}
    contentSecurityPolicy: {{ . | quote }}
    {{- end }}
{{- end }}
