-keep class com.yaytsa.app.** { *; }
-keepattributes *Annotation*
-dontwarn androidx.**
-dontwarn com.google.android.material.**
-dontwarn javax.annotation.Nullable
-dontwarn javax.annotation.concurrent.GuardedBy
